version: '3.8'

services:
  express-server:
    image: 755874648034.dkr.ecr.us-east-1.amazonaws.com/test-repo/express-server
    container_name: express-server
    ports:
      - '3001:3001'
    depends_on:
      - mongo-db
    environment:
      - MONGODB_URI=mongodb://mongo-db:27017

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: